"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, Shield, Zap, Star, Volume2, Play, Pause } from 'lucide-react';
import { Progress } from '@/components/ui/progress';
import { words, speak, type Word } from './words';
import WordReactor from './word-reactor';
import { lessonWords } from '@/lib/review-schedule';
import type { Progress as WordProgress } from './words';
import { shuffle } from '@/lib/random';
const pick=(pool:Word[])=>pool[Math.floor(Math.random()*pool.length)];
function options(w:Word,pool:Word[]=words){return shuffle([w,...shuffle(pool.filter(x=>x.en!==w.en)).slice(0,3)])}
type GameProps={vocabulary?:Word[];progress?:WordProgress;onAnswer?:(word:Word,correct:boolean,mode:string)=>void};
export default function Games({vocabulary=words,progress={},onAnswer}:GameProps){const [mode,setMode]=useState('');return <><div className="section-heading"><div><p className="eyebrow">A LITTLE PRACTICE. A LOT OF PLAY.</p><h2>Your word playground</h2></div><span className="pill">5 games</span></div>{!mode?<div className="game-menu">{[
['reactor','🏹','Word Reactor','Explore Lantern Street as an archer. Practise words to power up.','像弓箭手一样守护灯笼街，练习单词，选择升级。','reactor-tile'],
['match','🧩','Word Match','Find the English word for a Chinese meaning.','找出对应的英文单词。','mint'],['spell','🔤','Letter Builder','Put the letters in order to build a word.','点击字母，拼出单词。','yellow'],['ward','🛡️','Word Guardians','Dodge the dots. Learn words to power your shield.','躲开小圆点，答题升级护盾。','purple'],['sprint','⭐','Star Sprint','Collect stars and dodge dots. Answer to earn upgrades.','收集星星，答题获得升级。','blue']
].map(([id,icon,title,desc,zh,color])=><button className={'game-tile '+color} key={id} onClick={()=>setMode(id)}><span className="tile-icon">{icon}</span><span className="tile-heading">{title}</span><span>{desc}</span><span lang="zh-CN">{zh}</span><span className="tile-play">Play now <Play size={16}/></span></button>)}</div>:<><button className="back-button" onClick={()=>setMode('')}><ArrowLeft size={18}/>All games 所有游戏</button>{mode==='reactor'?<WordReactor vocabulary={vocabulary} progress={progress} onAnswer={onAnswer}/>:mode==='match'||mode==='spell'?<Quiz key={mode} mode={mode} vocabulary={vocabulary} progress={progress} onAnswer={onAnswer}/>:<Survival key={mode} mode={mode} vocabulary={vocabulary} onAnswer={onAnswer}/>}</>}</>}
function Quiz({mode,vocabulary=words,progress={},onAnswer}:{mode:string}&GameProps){
 const [list,setList]=useState<Word[]>([]),[round,setRound]=useState(0),[choices,setChoices]=useState<Word[]>([]),[letters,setLetters]=useState<string[]>([]),[used,setUsed]=useState<number[]>([]),[feedback,setFeedback]=useState(''),[correct,setCorrect]=useState(false),[mistake,setMistake]=useState(false),[score,setScore]=useState(0);
 useEffect(()=>{setList(shuffle(lessonWords(vocabulary,progress,Date.now())))},[vocabulary]);
 const w=list[round];useEffect(()=>{if(!w)return;setChoices(options(w,vocabulary));setLetters(shuffle((mode==='spell'?w.en.replace(/\s+/g,''):w.en).split('')));setUsed([]);setFeedback('');setCorrect(false);setMistake(false)},[w]);
 function check(answer:string){if(correct)return;const expected=mode==='spell'?w.en.replace(/\s+/g,''):w.en;onAnswer?.(w,answer===expected,mode);if(answer===expected){setCorrect(true);if(!mistake)setScore(s=>s+1);setFeedback('You got it! 答对啦！');speak(w.en)}else{setMistake(true);setFeedback('Keep trying! 再试一次。')}}
 if(list.length>0&&round>=list.length)return <div className="empty"><Star size={42}/><h2>Adventure complete!</h2><p>{score} of {list.length} words on your first try. Every try helps you learn.</p><button className="primary" onClick={()=>{setList(shuffle(vocabulary).slice(0,6));setRound(0);setScore(0)}}>Play again 再玩一次</button></div>;
 if(!w)return <p>Getting your words ready…</p>;
 return <section className="quiz-surface"><div className="quiz-top"><h3>{mode==='match'?'Word Match':'Letter Builder'}</h3><span>{round+1} / {list.length}</span></div><Progress value={round/list.length*100} aria-label="Questions completed"/><span className="word-emoji">{w.icon}</span><h2 lang="zh-CN">{w.zh}</h2><p>{mode==='match'?'Choose the English word.':'Tap the letters in order. 点击字母拼单词。'}</p>{mode==='match'?<div className="answers">{choices.map(x=><button key={x.en} disabled={correct} className={correct&&x.en===w.en?'answer-correct':''} onClick={()=>check(x.en)}>{x.en}</button>)}</div>:<><div className="spelling-output" aria-live="polite">{used.map(i=>letters[i]).join('')||'…'}</div><div className="letters">{letters.map((l,i)=><button key={i} disabled={used.includes(i)||correct} onClick={()=>{const n=[...used,i];setUsed(n);if(n.length===letters.length)check(n.map(x=>letters[x]).join(''))}}>{l}</button>)}</div><button disabled={correct||used.length===0} onClick={()=>{setUsed([]);setFeedback('')}}>Try letters again 重拼</button></>}<p className="feedback" aria-live="polite">{feedback}</p>{correct&&<button className="primary" onClick={()=>setRound(r=>r+1)}>{round===list.length-1?'Finish 完成':'Next word 下一个'}</button>}<button className="hear-hint" onClick={()=>speak(w.en)}><Volume2 size={18}/>Listen for a hint 听提示</button></section>
}
type Dot={x:number;y:number;id:number};
type GameState={x:number;y:number;time:number;hearts:number;level:number;score:number;enemies:Dot[];stars:Dot[];spawn:number;pulse:number;invincible:number;nextQuiz:number;id:number};
export const freshGame=():GameState=>({x:300,y:210,time:0,hearts:3,level:1,score:0,enemies:[],stars:[],spawn:0,pulse:0,invincible:0,nextQuiz:10,id:0});
function Survival({mode,vocabulary=words,onAnswer}:{mode:string}&GameProps){
 const canvas=useRef<HTMLCanvasElement>(null),game=useRef(freshGame()),keys=useRef(new Set<string>()),target=useRef<{x:number;y:number}|null>(null),statusRef=useRef('ready');
 const [status,setStatus]=useState('ready'),[hud,setHud]=useState({time:0,hearts:3,level:1,score:0}),[quiz,setQuiz]=useState<Word|null>(null),[choices,setChoices]=useState<Word[]>([]),[hint,setHint]=useState('');
 function change(s:string){statusRef.current=s;setStatus(s);keys.current.clear();target.current=null}
 function start(){game.current=freshGame();setQuiz(null);setHint('');setHud({time:0,hearts:3,level:1,score:0});change('playing')}
 useEffect(()=>{
 const down=(e:KeyboardEvent)=>{if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight','w','a','s','d'].includes(e.key)&&statusRef.current==='playing'){e.preventDefault();keys.current.add(e.key)}};const up=(e:KeyboardEvent)=>keys.current.delete(e.key);
 const blur=()=>{if(statusRef.current==='playing')change('paused');keys.current.clear()};
 window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',blur);document.addEventListener('visibilitychange',blur);
 let frame=0,last=performance.now(),ui=0;
 const loop=(now:number)=>{
 const dt=Math.min((now-last)/1000,.05);last=now;const g=game.current;const ctx=canvas.current?.getContext('2d');
 if(statusRef.current==='playing'){
 g.time+=dt;g.spawn+=dt;g.pulse+=dt;g.invincible=Math.max(0,g.invincible-dt);
 let dx=Number(keys.current.has('ArrowRight')||keys.current.has('d'))-Number(keys.current.has('ArrowLeft')||keys.current.has('a')),dy=Number(keys.current.has('ArrowDown')||keys.current.has('s'))-Number(keys.current.has('ArrowUp')||keys.current.has('w'));
 if(target.current){dx=target.current.x-g.x;dy=target.current.y-g.y;if(Math.hypot(dx,dy)<5){dx=0;dy=0}}const norm=Math.hypot(dx,dy);const speed=110+(mode==='sprint'?g.level*12:0);if(norm){g.x+=dx/norm*speed*dt;g.y+=dy/norm*speed*dt}g.x=Math.max(18,Math.min(582,g.x));g.y=Math.max(18,Math.min(402,g.y));
 if(g.spawn>1.2){g.spawn=0;const edge=Math.floor(Math.random()*4);g.enemies.push({x:edge===0?0:edge===1?600:Math.random()*600,y:edge===2?0:edge===3?420:Math.random()*420,id:g.id++});if(mode==='sprint'&&g.stars.length<6)g.stars.push({x:35+Math.random()*530,y:35+Math.random()*350,id:g.id++})}
 for(const e of g.enemies){const n=Math.hypot(g.x-e.x,g.y-e.y)||1;const speed=28+g.time*.35;e.x+=(g.x-e.x)/n*speed*dt;e.y+=(g.y-e.y)/n*speed*dt}
 if(mode==='ward'&&g.pulse>1.6){g.pulse=0;const range=70+g.level*15;const before=g.enemies.length;g.enemies=g.enemies.filter(e=>Math.hypot(g.x-e.x,g.y-e.y)>range);g.score+=before-g.enemies.length}
 if(g.invincible===0&&g.enemies.some(e=>Math.hypot(g.x-e.x,g.y-e.y)<25)){g.hearts--;g.invincible=2;g.enemies=g.enemies.filter(e=>Math.hypot(g.x-e.x,g.y-e.y)>60)}
 g.stars=g.stars.filter(s=>{if(Math.hypot(g.x-s.x,g.y-s.y)<26){g.score+=5;return false}return true});
 if(g.hearts<=0)change('lost');else if(g.time>=60)change('won');else if(g.time>=g.nextQuiz){const w=pick(vocabulary);setQuiz(w);setChoices(options(w,vocabulary));setHint('');g.nextQuiz+=10;change('quiz')}
 }
 if(ctx){ctx.clearRect(0,0,600,420);ctx.fillStyle=mode==='ward'?'#202044':'#163449';ctx.fillRect(0,0,600,420);ctx.strokeStyle='#ffffff0c';for(let x=0;x<600;x+=30){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,420);ctx.stroke()}for(let y=0;y<420;y+=30){ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(600,y);ctx.stroke()}
 for(const e of g.enemies){ctx.fillStyle='#ffad9c';ctx.beginPath();ctx.arc(e.x,e.y,11,0,Math.PI*2);ctx.fill();ctx.fillStyle='#202044';ctx.font='bold 14px Arial';ctx.textAlign='center';ctx.fillText('×',e.x,e.y+5)}
 for(const s of g.stars){ctx.fillStyle='#ffdf76';ctx.font='24px Arial';ctx.textAlign='center';ctx.fillText('★',s.x,s.y+8)}
 if(mode==='ward'){ctx.strokeStyle='#a394ff';ctx.lineWidth=2;ctx.beginPath();ctx.arc(g.x,g.y,(70+g.level*15)*(g.pulse/1.6),0,Math.PI*2);ctx.stroke()}
 ctx.globalAlpha=g.invincible>0?.55:1;ctx.fillStyle='#85eed4';ctx.beginPath();ctx.arc(g.x,g.y,16,0,Math.PI*2);ctx.fill();ctx.globalAlpha=1;ctx.fillStyle='#163449';ctx.font='bold 10px Arial';ctx.textAlign='center';ctx.fillText('YOU',g.x,g.y+4);
 }
 if(now-ui>120){ui=now;setHud({time:Math.min(60,Math.floor(g.time)),hearts:g.hearts,level:g.level,score:g.score})}frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);
 return()=>{cancelAnimationFrame(frame);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',blur);document.removeEventListener('visibilitychange',blur);keys.current.clear()}
 },[mode,vocabulary]);
 function answer(x:Word){if(!quiz)return;onAnswer?.(quiz,x.en===quiz.en,mode);if(x.en!==quiz.en){setHint('Try again. '+quiz.zh+' means '+quiz.en+'.');return}const g=game.current;g.level++;g.hearts=Math.min(3,g.hearts+1);g.enemies=[];g.score+=10;setQuiz(null);speak(quiz.en);change('playing')}
 function pointer(e:React.PointerEvent<HTMLCanvasElement>){const r=e.currentTarget.getBoundingClientRect();target.current={x:(e.clientX-r.left)/r.width*600,y:(e.clientY-r.top)/r.height*420}}
 return <section className="survival"><div className="quiz-top"><h3>{mode==='ward'?'Word Guardians':'Star Sprint'}</h3><span>60-second adventure</span></div><div className="hud"><span><Shield size={18}/>{hud.hearts} / 3</span><span><Zap size={18}/>Level {hud.level}</span><span><Star size={18}/>{hud.score}</span><span>{60-hud.time}s left</span></div><div className={'arena '+(status==='playing'?'':'with-overlay')}><canvas ref={canvas} width={600} height={420} aria-label="Game arena. Move with the direction buttons or arrow keys." onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pointer(e)}} onPointerMove={e=>{if(e.buttons)pointer(e)}} onPointerUp={()=>target.current=null} onPointerCancel={()=>target.current=null} onLostPointerCapture={()=>target.current=null}/>{status!=='playing'&&<div className="game-overlay">{status==='ready'?<><h2>{mode==='ward'?'Protect your words!':'Collect the stars!'}</h2><p>{mode==='ward'?'Your shield clears nearby dots automatically.':'Collect yellow stars and avoid pink dots.'}</p><p>Answer a word every 10 seconds to level up.<br/>每10秒答一道单词题，升级并恢复护盾。</p><button className="primary" onClick={start}>Start adventure 开始</button></>:status==='quiz'&&quiz?<><p className="eyebrow">UPGRADE TIME · 升级时间</p><h2 lang="zh-CN">{quiz.zh}</h2><p>Which word matches?</p><div className="answers">{choices.map(x=><button key={x.en} onClick={()=>answer(x)}>{x.en}</button>)}</div><p aria-live="polite">{hint}</p></>:status==='paused'?<><h2>Take a breath.</h2><button className="primary" onClick={()=>change('playing')}>Resume 继续</button></>:<><h2>{status==='won'?'Adventure complete!':'Good adventure!'}</h2><p>You earned {hud.score} points and reached level {hud.level}.</p><p>Try again to practice more words. 再来一次吧！</p><button className="primary" onClick={start}>Play again 再玩一次</button></>}</div>}</div><div className="game-controls"><div className="dpad">{[['ArrowLeft','←'],['ArrowUp','↑'],['ArrowDown','↓'],['ArrowRight','→']].map(([key,label])=><button key={key} aria-label={'Move '+key.replace('Arrow','').toLowerCase()} disabled={status!=='playing'} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);keys.current.add(key)}} onPointerUp={()=>keys.current.delete(key)} onPointerCancel={()=>keys.current.delete(key)} onLostPointerCapture={()=>keys.current.delete(key)}>{label}</button>)}</div><button disabled={status!=='playing'} onClick={()=>change('paused')}><Pause size={18}/>Pause</button></div><p className="instructions">Hold a direction button or drag in the arena to move. 按住方向键或拖动。<br/>On a computer, use arrow keys or WASD.</p></section>
}
