"use client";
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Volume2,ArrowRight,Check} from 'lucide-react';
import {speak,stopSpeaking,type Word,type Progress} from './words';
import {shuffle} from '@/lib/random';
import {reviewCards} from '@/lib/review-schedule';
import {publicAsset} from '@/lib/public-runtime';
import {spokenMatch} from '@/lib/unit-activities';
type Recognition={lang:string;interimResults:boolean;continuous:boolean;onresult:((e:{results:{[i:number]:{[i:number]:{transcript:string}}}})=>void)|null;onerror:((e:{error:string})=>void)|null;onend:(()=>void)|null;start:()=>void;abort:()=>void;stop:()=>void};
function recognitionConstructor(){return (window as unknown as {SpeechRecognition?:new()=>Recognition;webkitSpeechRecognition?:new()=>Recognition}).SpeechRecognition||(window as unknown as {webkitSpeechRecognition?:new()=>Recognition}).webkitSpeechRecognition;}
export default function PicturePractice({mode,vocabulary,progress,onAnswer}:{mode:'picture-speak'|'picture-listen'|'word-choice';vocabulary:Word[];progress:Progress;onAnswer:(w:Word,correct:boolean,mode:string)=>Promise<void>}){
 const [queue,setQueue]=useState(()=>reviewCards(vocabulary,progress,Date.now()));
 const marked=useRef(false);
 const [round,setRound]=useState(0),[choices,setChoices]=useState<Word[]>([]),[selected,setSelected]=useState(-1),[result,setResult]=useState<boolean|null>(null),[message,setMessage]=useState(''),[recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[url,setUrl]=useState(''),[transcript,setTranscript]=useState(''),[consent,setConsent]=useState(false),[canCheck,setCanCheck]=useState(false),[canRecord,setCanRecord]=useState(false);
 const generation=useRef(0);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),recognition=useRef<Recognition|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true),checked=useRef(false);
 const w=queue[round];const soundPrompt=mode==='word-choice'&&round%2===1;
 useEffect(()=>{alive.current=true;setCanCheck(Boolean(recognitionConstructor()));setCanRecord(typeof navigator.mediaDevices?.getUserMedia==='function'&&typeof window.MediaRecorder!=='undefined');return()=>{alive.current=false;generation.current++;recognition.current?.abort();if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());stopSpeaking()}},[]);
 useEffect(()=>{generation.current++;recognition.current?.abort();
 marked.current=false;if(!w)return;
 setChoices(shuffle([w,...shuffle(vocabulary.filter(x=>x.en!==w.en)).slice(0,3)]));setSelected(-1);setResult(null);setMessage('');setTranscript('');setUrl('');checked.current=false},[w,vocabulary]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 function stop(){if(timer.current)clearTimeout(timer.current);recognition.current?.stop();if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setRecording(false)}
 async function mark(correct:boolean){setResult(correct);setMessage(correct?'⭐ Well done! 答对了！':'💛 Listen and try again. 听一听，再试试。');try{if(!marked.current){marked.current=true;await onAnswer(w,correct,mode);}}catch{marked.current=false;setResult(null);setMessage('Your answer could not be saved. Please try again.')}}
 async function start(){if(!canRecord)return;const attempt=++generation.current;recognition.current?.abort();stopSpeaking();setBusy(true);setMessage('');setResult(null);setTranscript('');setUrl('');checked.current=false;try{
 const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current||attempt!==generation.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;
 const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const r=new MediaRecorder(media,mime?{mimeType:mime}:undefined);recorder.current=r;const chunks:Blob[]=[];
 r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};r.onstop=()=>{media.getTracks().forEach(t=>t.stop());if(!alive.current||attempt!==generation.current)return;setRecording(false);if(timer.current)clearTimeout(timer.current);const blob=new Blob(chunks,{type:r.mimeType});if(blob.size)setUrl(URL.createObjectURL(blob))};r.onerror=()=>{stop();setMessage('Recording stopped. Try again. 录音中断，请重试。')};r.start();setRecording(true);
 const Constructor=recognitionConstructor();if(Constructor&&consent){const rec=new Constructor();recognition.current=rec;rec.lang='en-US';rec.interimResults=false;rec.continuous=false;rec.onresult=e=>{if(!alive.current||attempt!==generation.current||checked.current)return;checked.current=true;const heard=e.results[0][0].transcript;setTranscript(heard);void mark(spokenMatch(heard,w.en));stop()};rec.onerror=()=>{if(alive.current&&attempt===generation.current&&!checked.current){checked.current=true;setMessage('Could not check this recording. Listen back or ask your teacher. 无法检查，请回放或请老师听。')}};rec.onend=()=>{if(alive.current&&attempt===generation.current&&!checked.current)setMessage('No answer was recognized. Try again or listen back. 没有识别到答案，请重试。')};try{rec.start()}catch{setMessage('Automatic checking is unavailable. You can still record and listen.')}}
 timer.current=setTimeout(stop,10000);
 }catch{setMessage('Please allow microphone access. 请允许使用麦克风。')}finally{if(alive.current)setBusy(false)}}
 if(!w)return <section className="empty"><h2>⭐ Review complete! 复习完成！</h2><p>New words and due words appear here. Remembered words return later; missed words return in ten minutes.</p><button onClick={()=>{setQueue(reviewCards(vocabulary,progress,Date.now()));setRound(0)}}>Check for due cards 查看待复习卡片</button></section>;
 return <section className="picture-surface"><div className="quiz-top"><h2>{mode==='picture-speak'?'Look & say 看图说英语':mode==='word-choice'?'Choose a word 选单词':'Look & listen 看图听音'}</h2><span>{round+1} / {queue.length} due cards</span></div><p className="small-note">Spaced review · 间隔复习</p>{soundPrompt?<button className="picture-prompt audio-prompt" aria-label="Listen to the flashcard" onClick={()=>speak(w.en)}><Volume2 size={72}/></button>:<div className="picture-prompt" role="img" aria-label="Vocabulary picture">{w.picture?<img src={publicAsset(w.picture)} alt="" decoding="async"/>:w.icon}</div>}
 {mode!=='picture-speak'?<><p>{mode==='word-choice'?(soundPrompt?'Listen, then choose the word.':'Look at the picture, then choose the word.'):'🔊 → OK · Tap a sound to choose it, then tap OK. 点击声音选择答案，再点击 OK。'}</p><div className="sound-choices">{choices.map((x,i)=><div key={x.en} className={selected===i?'sound-choice selected':'sound-choice'}>{mode==='word-choice'?<button className="written-choice" disabled={result===true} aria-pressed={selected===i} onClick={()=>{setSelected(i);setResult(null);setMessage('')}}>{x.en}</button>:<button className="sound-answer" aria-label={'Listen to sound '+(i+1)} aria-pressed={selected===i} disabled={result===true} onClick={()=>{setSelected(i);setResult(null);setMessage('');speak(x.en)}}><Volume2 size={38}/><span>{i+1}</span>{selected===i&&<Check aria-hidden="true"/>}</button>}</div>)}</div><button className="primary" disabled={selected<0||result===true} onClick={()=>void mark(choices[selected].en===w.en)}>OK ✓</button></>:<><p>🎤 Say it in English! 用英语说一说。</p><button className="primary" disabled={busy||!canRecord} onClick={recording?stop:()=>void start()}>{recording?<Square/>:<Mic/>}{recording?'Stop 停止':'Record 录音'}</button>{!canRecord&&<p className="notice">This browser cannot record. Try another browser with microphone access.</p>}{url&&<audio controls src={url}/>}<div className="parent-note">{canCheck?<label><input type="checkbox" checked={consent} disabled={busy||recording} onChange={e=>setConsent(e.target.checked)}/> Parent/teacher: enable browser speech checking. Audio may go to the browser’s speech provider. 家长或老师：允许语音检查。</label>:<p>Automatic checking is not connected in this browser. Record and listen with your teacher. 此浏览器尚未连接自动检查，可录音后请老师听。</p>}<p>Speech recognition may mishear children. This checks the word, not pronunciation.</p></div>{transcript&&<p>Heard: {transcript}</p>}{url&&result===null&&<div className="parent-note"><p>Teacher/parent: listen, then rate this card to schedule its next review.</p><button disabled={busy||recording} onClick={()=>void mark(true)}>Remembered ✓</button><button disabled={busy||recording} onClick={()=>void mark(false)}>Practise again ↻</button></div>}<button disabled={recording||busy} onClick={()=>speak(w.en)}><Volume2/> Listen to the answer 听答案</button></>}
 <p className="feedback" aria-live="polite">{message}</p><button disabled={recording||busy||(mode!=='picture-speak'&&result!==true)} onClick={()=>setRound(r=>r+1)}><ArrowRight/> Next 下一题</button></section>
}
