"use client";
import {useEffect,useRef,useState} from 'react';
import {Mic,Square,Volume2,ArrowRight,Check} from 'lucide-react';
import {speak,stopSpeaking,type Word,type Progress} from './words';
import {shuffle} from '@/lib/random';
import {reviewCards} from '@/lib/review-schedule';
import {publicAsset} from '@/lib/public-runtime';
import {spokenMatch} from '@/lib/unit-activities';
import {speechEndpoint,checkSpeech} from '@/lib/speech-check';
import {recordingLevel} from '@/lib/recording-level';
export default function PicturePractice({mode,vocabulary,progress,onAnswer}:{mode:'picture-speak'|'picture-listen'|'word-choice';vocabulary:Word[];progress:Progress;onAnswer:(w:Word,correct:boolean,mode:string)=>Promise<void>}){
 const [queue,setQueue]=useState(()=>reviewCards(vocabulary,progress,Date.now()));
 const marked=useRef(false);
 const [round,setRound]=useState(0),[choices,setChoices]=useState<Word[]>([]),[selected,setSelected]=useState(-1),[result,setResult]=useState<boolean|null>(null),[message,setMessage]=useState(''),[recording,setRecording]=useState(false),[busy,setBusy]=useState(false),[url,setUrl]=useState(''),[transcript,setTranscript]=useState(''),[consent,setConsent]=useState(false),[endpoint,setEndpoint]=useState(''),[endpointLoading,setEndpointLoading]=useState(true),[canRecord,setCanRecord]=useState(false);
 const generation=useRef(0);
 const level=useRef<Awaited<ReturnType<typeof recordingLevel>>>(null);
 const recorder=useRef<MediaRecorder|null>(null),stream=useRef<MediaStream|null>(null),request=useRef<AbortController|null>(null),timer=useRef<ReturnType<typeof setTimeout>|null>(null),alive=useRef(true);
 const w=queue[round];const soundPrompt=mode==='word-choice'&&round%2===1;
 useEffect(()=>{alive.current=true;void speechEndpoint().then(value=>{if(alive.current){setEndpoint(value);setCanRecord(typeof navigator.mediaDevices?.getUserMedia==='function'&&typeof window.MediaRecorder!=='undefined')}}).catch(()=>{if(alive.current)setCanRecord(typeof navigator.mediaDevices?.getUserMedia==='function'&&typeof window.MediaRecorder!=='undefined')}).finally(()=>{if(alive.current)setEndpointLoading(false)});return()=>{alive.current=false;generation.current++;request.current?.abort();level.current?.close();if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());stopSpeaking()}},[]);
 // Reset the current answer when the parent supplies a different review card.
 useEffect(()=>{generation.current++;request.current?.abort();
 marked.current=false;if(!w)return;
 // eslint-disable-next-line react-hooks/set-state-in-effect
 setChoices(shuffle([w,...shuffle(vocabulary.filter(x=>x.en!==w.en)).slice(0,3)]));setSelected(-1);setResult(null);setMessage('');setTranscript('');setUrl('')},[w,vocabulary]);
 useEffect(()=>()=>{if(url)URL.revokeObjectURL(url)},[url]);
 function stop(){if(timer.current)clearTimeout(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setRecording(false)}
 async function mark(correct:boolean){setResult(correct);setMessage(correct?'⭐ Well done! 答对了！':'💛 Listen and try again. 听一听，再试试。');try{if(!marked.current){marked.current=true;await onAnswer(w,correct,mode);}}catch{marked.current=false;setResult(null);setMessage('Your answer could not be saved. Please try again.')}}
 async function start(){if(!canRecord)return;const attempt=++generation.current;request.current?.abort();stopSpeaking();setBusy(true);setMessage('');setResult(null);setTranscript('');setUrl('');try{
 const media=await navigator.mediaDevices.getUserMedia({audio:true});if(!alive.current||attempt!==generation.current){media.getTracks().forEach(t=>t.stop());return}stream.current=media;level.current=await recordingLevel(media);if(!alive.current||attempt!==generation.current){level.current?.close();media.getTracks().forEach(t=>t.stop());return}
 const mime=['audio/mp4','audio/webm;codecs=opus','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));const r=new MediaRecorder(media,mime?{mimeType:mime}:undefined);recorder.current=r;const chunks:Blob[]=[];
 let recordingFailed=false;
 r.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};
 r.onstop=()=>{const hasSound=level.current?.hasSound()??true;level.current?.close();level.current=null;media.getTracks().forEach(t=>t.stop());if(!alive.current||attempt!==generation.current)return;setRecording(false);if(timer.current)clearTimeout(timer.current);const blob=new Blob(chunks,{type:r.mimeType});if(!blob.size||recordingFailed){setMessage('No recording was saved. Try again. 没有保存录音，请重试。');return}setUrl(URL.createObjectURL(blob));
 if(consent&&endpoint&&!hasSound){setMessage('💛 I couldn’t hear clearly. Please try again! 没听清，请再试一次！');return}
 if(consent&&endpoint){setBusy(true);setMessage('✨ Checking… 正在检查…');const controller=new AbortController();request.current=controller;const timeout=setTimeout(()=>controller.abort(),25000);
 void checkSpeech(endpoint,blob,controller.signal).then(answer=>{if(!alive.current||attempt!==generation.current)return;if(answer.status==='unclear'){setMessage('💛 I couldn’t hear clearly. Please try again! 没听清，请再试一次！');return}setTranscript(answer.transcript);return mark(spokenMatch(answer.transcript,w.en));}).catch(error=>{if(!alive.current||attempt!==generation.current)return;setMessage(error instanceof Error&&error.message==='busy'?'The checker is busy or its free allowance is used up. Try later. 检查服务繁忙或免费额度已用完，请稍后重试。':'Could not check this recording. Please try again or ask your teacher. 无法检查，请重试或请老师听。');}).finally(()=>{clearTimeout(timeout);if(alive.current&&attempt===generation.current)setBusy(false)});
 }else setMessage(endpoint?'Recording saved. Enable voice checking to get an automatic result. 录音已保存，开启语音检查后可自动检查。':'Recording saved. Automatic checking is not connected yet. 录音已保存，自动检查尚未连接。');
 };
 r.onerror=()=>{recordingFailed=true;stop();setMessage('Recording stopped. Try again. 录音中断，请重试。')};r.start();setRecording(true);timer.current=setTimeout(stop,10000);
 }catch{level.current?.close();level.current=null;stream.current?.getTracks().forEach(t=>t.stop());setMessage('Please allow microphone access. 请允许使用麦克风。')}finally{if(alive.current&&attempt===generation.current)setBusy(false)}}
 if(!w)return <section className="empty"><h2>⭐ Review complete! 复习完成！</h2><p>New words and due words appear here. Remembered words return later; missed words return in ten minutes.</p><button onClick={()=>{setQueue(reviewCards(vocabulary,progress,Date.now()));setRound(0)}}>Check for due cards 查看待复习卡片</button></section>;
 return <section className="picture-surface"><div className="quiz-top"><h2>{mode==='picture-speak'?'Look & say 看图说英语':mode==='word-choice'?'Choose a word 选单词':'Look & listen 看图听音'}</h2><span>{round+1} / {queue.length} due cards</span></div><p className="small-note">Spaced review · 间隔复习</p>{soundPrompt?<button className="picture-prompt audio-prompt" aria-label="Listen to the flashcard" onClick={()=>speak(w.en)}><Volume2 size={72}/></button>:<div className="picture-prompt" role="img" aria-label="Vocabulary picture">{w.picture?<img src={publicAsset(w.picture)} alt="" decoding="async"/>:w.icon}</div>}
 {mode!=='picture-speak'?<><p>{mode==='word-choice'?(soundPrompt?'Listen, then choose the word.':'Look at the picture, then choose the word.'):'🔊 → OK · Tap a sound to choose it, then tap OK. 点击声音选择答案，再点击 OK。'}</p><div className="sound-choices">{choices.map((x,i)=><div key={x.en} className={selected===i?'sound-choice selected':'sound-choice'}>{mode==='word-choice'?<button className="written-choice" disabled={result===true} aria-pressed={selected===i} onClick={()=>{setSelected(i);setResult(null);setMessage('')}}>{x.en}</button>:<button className="sound-answer" aria-label={'Listen to sound '+(i+1)} aria-pressed={selected===i} disabled={result===true} onClick={()=>{setSelected(i);setResult(null);setMessage('');speak(x.en)}}><Volume2 size={38}/><span>{i+1}</span>{selected===i&&<Check aria-hidden="true"/>}</button>}</div>)}</div><button className="primary" disabled={selected<0||result===true} onClick={()=>void mark(choices[selected].en===w.en)}>OK ✓</button></>:<><p>🎤 Say it in English! 用英语说一说。</p><button className="primary" disabled={busy||endpointLoading||!canRecord} onClick={recording?stop:()=>void start()}>{recording?<Square/>:<Mic/>}{recording?'Stop 停止':busy?'Checking… 检查中…':'Record 录音'}</button>{!canRecord&&<p className="notice">This browser cannot record. Try another browser with microphone access.</p>}{url&&<audio controls src={url}/>}<div className="parent-note">{endpoint?<label><input type="checkbox" checked={consent} disabled={busy||recording} onChange={e=>setConsent(e.target.checked)}/> Parent/teacher: enable automatic voice checking. Recordings are sent through Cloudflare to Groq to recognize the word. 家长或老师：允许上传录音进行语音检查。</label>:<p>{endpointLoading?'Preparing voice checking…':'Automatic checking is not connected yet. Record and listen with your teacher. 自动检查尚未连接，可录音后请老师听。'}</p>}<p>Speech recognition may mishear children. This checks the word, not pronunciation.</p></div>{transcript&&<p>Heard: {transcript}</p>}{url&&result===null&&!busy&&<div className="parent-note"><p>Teacher/parent: listen, then rate this card to schedule its next review.</p><button disabled={busy||recording} onClick={()=>void mark(true)}>Remembered ✓</button><button disabled={busy||recording} onClick={()=>void mark(false)}>Practise again ↻</button></div>}<button disabled={recording||busy} onClick={()=>speak(w.en)}><Volume2/> Listen to the answer 听答案</button></>}
 <p className="feedback" aria-live="polite">{message}</p><button disabled={recording||busy||(mode!=='picture-speak'&&result!==true)} onClick={()=>setRound(r=>r+1)}><ArrowRight/> Next 下一题</button></section>
}
