import {useEffect,useState} from 'react';
import QRCode from 'qrcode';
import {activityOptions,allActivities,youngActivities,settingsLink,type Settings,type UnitSettings} from '../lib/unit-activities';
import {lessons} from './lessons';
export default function Teacher({settings,onSave,onExit}:{settings:Settings;onSave:(settings:Settings)=>void;onExit:()=>void}){
 const [book,setBook]=useState(lessons[0].book),[id,setId]=useState(lessons[0].id),[draft,setDraft]=useState(settings),[message,setMessage]=useState(''),[link,setLink]=useState(''),[qr,setQr]=useState('');
 const lesson=lessons.find(l=>l.id===id)!;const value=draft[id]||{age:'7–12',activities:allActivities};
 function update(patch:Partial<UnitSettings>){setDraft(prev=>({...prev,[id]:{...value,...patch}}));setLink('');setMessage('Unsaved changes');}
 useEffect(()=>{setLink('');setQr('');setMessage('')},[id]);
 useEffect(()=>{let active=true;setQr('');if(link)QRCode.toDataURL(link,{width:320,margin:3,errorCorrectionLevel:'M'}).then(data=>{if(active)setQr(data)}).catch(()=>setMessage('Could not create QR. Use the link instead.'));return()=>{active=false}},[link]);
 function save(){try{onSave(draft);setMessage('Saved on this browser. Use the student link to share these choices.')}catch{setMessage('Could not save settings. Browser storage may be full or blocked.')}}
 function share(){try{onSave(draft);setLink(settingsLink({[id]:value},id));setMessage('Share this link or QR with students. Later edits need a new link.')}catch{setMessage('Could not save settings.')}}
 return <section className="teacher-settings"><div className="section-heading"><div><p className="eyebrow">LESSON PLANNER</p><h1>Teacher view 老师设置</h1></div><button onClick={onExit}>Student view 学生页面</button></div><p className="notice">This is a lesson settings screen saved on your browser. A private teacher account and online student reports are not connected yet. Shared links contain activity choices only.</p><div className="teacher-selectors"><label>Book 课本<select value={book} onChange={e=>{const next=e.target.value;setBook(next);setId(lessons.find(l=>l.book===next)!.id)}}>{[...new Set(lessons.map(l=>l.book))].map(b=><option key={b}>{b}</option>)}</select></label><label>Unit 单元<select value={id} onChange={e=>setId(e.target.value)}>{lessons.filter(l=>l.book===book).map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select></label></div><h2>{lesson.title}</h2><label>Suggested ages 年龄<input value={value.age} maxLength={40} onChange={e=>update({age:e.target.value})}/></label><div className="teacher-presets"><button onClick={()=>update({age:'3–5',activities:youngActivities})}>Pre-readers · Ages 3–5</button><button onClick={()=>update({age:'7–12',activities:allActivities})}>Readers · Ages 7–12</button></div><div className="activity-settings">{activityOptions.map(([key,icon,title,description])=><label key={key}><input type="checkbox" checked={value.activities.includes(key)} onChange={e=>update({activities:e.target.checked?[...value.activities,key]:value.activities.filter(a=>a!==key)})}/><span><strong>{icon} {title}</strong><small>{description}</small></span></label>)}</div>{value.activities.length===0&&<p role="alert">Choose at least one activity.</p>}<p className="small-note">Picture exercises use each word’s current picture symbol. Choose concrete words with clear pictures for pre-readers. Action games currently require reading.</p><div className="teacher-presets"><button className="primary" disabled={!value.activities.length} onClick={save}>Save settings 保存</button><button disabled={!value.activities.length} onClick={share}>Create student link & QR 学生链接</button></div><p role="status">{message}</p>{link&&<div className="share-unit"><a href={link}>Open student lesson</a><input aria-label="Student lesson link" readOnly value={link} onFocus={e=>e.target.select()}/><button onClick={()=>navigator.clipboard.writeText(link).then(()=>setMessage('Link copied')).catch(()=>setMessage('Select and copy the link above.'))}>Copy link 复制</button>{qr&&<img src={qr} alt="QR code for this unit with selected activities"/>}</div>}</section>
}
